import { Cow, AlertNotification, VetCase, DistrictHotspot, SensorGatewayStatus } from '../types';

export const INITIAL_GATEWAY_STATUS: SensorGatewayStatus = {
  gatewayId: 'ESP32-C3-KR01',
  protocol: 'BLE / LoRa + MQTT',
  firmwareVersion: 'v2.4.1-edge-tflite',
  batteryPercent: 94,
  solarCharging: true,
  sdCardBufferedPackets: 4,
  lastSyncTimestamp: '2 mins ago',
  isOnline: true,
  packetLossRate: 0.2,
};

export const INITIAL_COWS: Cow[] = [
  {
    id: 42,
    tagNumber: 'IN-WB-2024-0042',
    name: 'Ganga',
    breed: 'Sahiwal',
    ageYears: 4.5,
    parity: 2,
    lactationDay: 118,
    currentMilkYield: 13.8,
    avgMilkYield: 15.5,
    riskScore: 82,
    riskLevel: 'HIGH',
    primaryQuarter: 'LR',
    sccCellsPerMl: 1850000,
    sccBand: '2+',
    tubeTempDiff: 1.8,
    milkEc: 6.85,
    ruminationMin: 385,
    ruminationDropPct: 18,
    activitySteps: 48,
    activityDropPct: 14,
    thiIndex: 76,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 06:40 AM',
    forecast14Days: [18, 20, 22, 25, 29, 34, 42, 48, 55, 62, 69, 74, 78, 82],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.1, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.2, ecValue: 5.2, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 1.8, ecValue: 6.85, sccBand: '2+', isAffected: true, statusText: 'Thermal + EC Spike' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.4, ecValue: 5.3, sccBand: 'Trace', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [
      {
        id: 'shap-1',
        featureKey: 'scc_trajectory',
        name: 'SCC Band Elevation',
        nameHi: 'सोमैटिक सेल (SCC) वृद्धि',
        nameBn: 'সোম্যাটিক সেল কাউন্ট বৃদ্ধি',
        impactWeight: 0.38,
        deltaValue: '+34% vs baseline',
        baselineValue: '180k cells/mL',
        currentValue: '1.85M cells/mL',
        explanation: 'CMT photo gel viscosity crossed 4 lakh threshold. Subclinical inflammatory response active.',
        direction: 'increase_risk',
      },
      {
        id: 'shap-2',
        featureKey: 'tube_thermal_diff',
        name: 'MLX90640 Tube Heat',
        nameHi: 'मिल्क-ट्यूब तापमान वृद्धि',
        nameBn: 'দুধের নালীতে তাপ বৃদ্ধি',
        impactWeight: 0.31,
        deltaValue: '+1.8°C vs other quarters',
        baselineValue: '36.1°C',
        currentValue: '37.9°C',
        explanation: 'Local hyperthermia detected inside LR milk tube. Bypasses hair & dung noise.',
        direction: 'increase_risk',
      },
      {
        id: 'shap-3',
        featureKey: 'rumination_drop',
        name: 'Rumination Drop',
        nameHi: 'जुगाली में गिरावट',
        nameBn: 'জাবর কাটার সময় হ্রাস',
        impactWeight: 0.19,
        deltaValue: '-18% vs 30-day mean',
        baselineValue: '470 min/day',
        currentValue: '385 min/day',
        explanation: 'Systemic discomfort signaled by neck collar accelerometer across past 48 hours.',
        direction: 'increase_risk',
      },
      {
        id: 'shap-4',
        featureKey: 'milk_ec_slope',
        name: 'Milk Conductivity (EC)',
        nameHi: 'दूध विद्युत चालकता (EC)',
        nameBn: 'দুধের তড়িৎ পরিবাহিতা',
        impactWeight: 0.12,
        deltaValue: '+1.75 mS/cm',
        baselineValue: '5.10 mS/cm',
        currentValue: '6.85 mS/cm',
        explanation: 'Disruption of blood-milk barrier leaking Na+ and Cl- ions into milk stream.',
        direction: 'increase_risk',
      },
    ],
    actionPlan: {
      urgency: 'HIGH',
      vetRecommended: true,
      stepsEn: [
        'Milk Left-Rear (LR) quarter last and collect milk in a dedicated secondary container.',
        'Apply 0.5% chlorhexidine / iodine barrier teat dip immediately after milking.',
        'Withhold LR quarter milk from bulk tank to protect cooperative milk grading.',
        'Veterinary consult booked: Dr. Meera Roy (Visit: Tomorrow 08:30 AM).',
      ],
      stepsHi: [
        'बाएं पिछले थन (LR) का दूध सबसे अंत में अलग बाल्टी में निकालें।',
        'दुहने के तुरंत बाद 0.5% क्लोरहेक्सिडिन / आयोडीन घोल में थन डुबोएं।',
        'इस थन का दूध मुख्य कैन में न मिलाएं ताकि दूध का ग्रेड खराब न हो।',
        'पशु चिकित्सक डॉ. मीरा रॉय से संपर्क करें (कल सुबह 08:30 बजे)।',
      ],
      stepsBn: [
        'বাঁ-দিকের পেছনের বাট (LR)-এর দুধ সবার শেষে আলাদা পাত্রে দোয়ান।',
        'দোহন শেষেই ০.৫% ক্লোরহেক্সিডিন সলিউশনে বাট ডুবিয়ে জীবাণুমুক্ত করুন।',
        'সমবায় দুধের মান রক্ষা করতে এই বাটের দুধ মূল ক্যানের সাথে মেশাবেন না।',
        'ডাক্তার মীরা রায়ের সাথে পরামর্শ স্থির হয়েছে (আগামীকাল সকাল ৮:৩০)।',
      ],
    },
  },
  {
    id: 55,
    tagNumber: 'IN-WB-2024-0055',
    name: 'Nandini',
    breed: 'Murrah',
    ageYears: 5.2,
    parity: 3,
    lactationDay: 92,
    currentMilkYield: 15.2,
    avgMilkYield: 16.8,
    riskScore: 74,
    riskLevel: 'HIGH',
    primaryQuarter: 'RR',
    sccCellsPerMl: 1250000,
    sccBand: '2+',
    tubeTempDiff: 1.4,
    milkEc: 6.4,
    ruminationMin: 410,
    ruminationDropPct: 12,
    activitySteps: 50,
    activityDropPct: 9,
    thiIndex: 78,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 06:21 AM',
    forecast14Days: [22, 24, 28, 31, 36, 42, 49, 56, 61, 65, 68, 71, 72, 74],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.3, ecValue: 5.2, sccBand: 'Trace', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.2, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 1.4, ecValue: 6.4, sccBand: '2+', isAffected: true, statusText: 'Moderate Thermal Heat' },
    },
    shapDrivers: [
      {
        id: 'shap-55-1',
        featureKey: 'tube_thermal_diff',
        name: 'Right Rear Tube Heat',
        nameHi: 'दाएं पिछले थन में ताप',
        nameBn: 'ডান পেছনের বাটে তাপ',
        impactWeight: 0.42,
        deltaValue: '+1.4°C vs baseline',
        baselineValue: '36.3°C',
        currentValue: '37.7°C',
        explanation: 'MLX90640 thermal sensor records steady quarter differential over 6 milkings.',
        direction: 'increase_risk',
      },
      {
        id: 'shap-55-2',
        featureKey: 'scc_trajectory',
        name: 'SCC Band 2+ Drift',
        nameHi: 'सोमैटिक सेल में उछाल',
        nameBn: 'এসসিসি বৃদ্ধি',
        impactWeight: 0.33,
        deltaValue: '+28% vs baseline',
        baselineValue: '210k cells/mL',
        currentValue: '1.25M cells/mL',
        explanation: 'CMT photo algorithm detected thickening gel in RR well.',
        direction: 'increase_risk',
      },
    ],
    actionPlan: {
      urgency: 'HIGH',
      vetRecommended: true,
      stepsEn: [
        'Isolate RR quarter milk during evening milking.',
        'Repeat CMT gel check before bedtime to confirm drift.',
        'Check bedding cleanliness in stall #4.',
      ],
      stepsHi: [
        'शाम के समय RR थन का दूध अलग रखें।',
        'रात को सोने से पहले सीएमटी टेस्ट दोहराएं।',
        'बाड़े की सफाई और सूखापन सुनिश्चित करें।',
      ],
      stepsBn: [
        'সন্ধ্যার দোহনে RR বাটের দুধ আলাদা রাখুন।',
        'ঘুমানোর আগে আরেকবার সিএমটি পরীক্ষা করুন।',
        'গোয়ালঘরের মেঝের শুষ্কতা ও পরিচ্ছন্নতা বজায় রাখুন।',
      ],
    },
  },
  {
    id: 17,
    tagNumber: 'IN-WB-2024-0017',
    name: 'Lakshmi',
    breed: 'Gir',
    ageYears: 3.8,
    parity: 1,
    lactationDay: 64,
    currentMilkYield: 11.4,
    avgMilkYield: 12.0,
    riskScore: 61,
    riskLevel: 'MODERATE',
    primaryQuarter: 'RF',
    sccCellsPerMl: 650000,
    sccBand: '1+',
    tubeTempDiff: 0.9,
    milkEc: 5.9,
    ruminationMin: 440,
    ruminationDropPct: 7,
    activitySteps: 55,
    activityDropPct: 5,
    thiIndex: 74,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 06:35 AM',
    forecast14Days: [19, 21, 23, 26, 30, 35, 41, 46, 50, 54, 57, 59, 60, 61],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.9, ecValue: 5.9, sccBand: '1+', isAffected: true, statusText: 'Watch Quarter' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.2, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [
      {
        id: 'shap-17-1',
        featureKey: 'milk_ec_slope',
        name: 'Conductivity Drift',
        nameHi: 'चालकता वृद्धि',
        nameBn: 'পরিবাহিতা বৃদ্ধি',
        impactWeight: 0.45,
        deltaValue: '+0.8 mS/cm',
        baselineValue: '5.1 mS/cm',
        currentValue: '5.9 mS/cm',
        explanation: '7-day upward slope without visible swelling.',
        direction: 'increase_risk',
      },
    ],
    actionPlan: {
      urgency: 'MODERATE',
      vetRecommended: false,
      stepsEn: [
        'Monitor RF quarter in tomorrow morning session.',
        'Use pre-milking iodine wipe and dry thoroughly.',
        'Run CMT scan if tube heat exceeds +1.0°C.',
      ],
      stepsHi: [
        'कल सुबह RF थन की विशेष निगरानी करें।',
        'दुहने से पहले थन को अच्छी तरह साफ व सूखा रखें।',
      ],
      stepsBn: [
        'আগামীকাল সকালে RF বাটে বিশেষ নজর রাখুন।',
        'দোহনের পূর্বে বাট পরিষ্কার ও শুকনো রাখুন।',
      ],
    },
  },
  {
    id: 29,
    tagNumber: 'IN-WB-2024-0029',
    name: 'Gauri',
    breed: 'HF Cross',
    ageYears: 4.1,
    parity: 2,
    lactationDay: 140,
    currentMilkYield: 18.2,
    avgMilkYield: 19.5,
    riskScore: 52,
    riskLevel: 'MODERATE',
    primaryQuarter: 'LF',
    sccCellsPerMl: 480000,
    sccBand: '1+',
    tubeTempDiff: 0.7,
    milkEc: 5.7,
    ruminationMin: 450,
    ruminationDropPct: 6,
    activitySteps: 58,
    activityDropPct: 4,
    thiIndex: 79,
    sensorStatus: 'BUFFERED_SD',
    lastMilkedTime: 'Today, 06:12 AM',
    forecast14Days: [25, 27, 29, 32, 34, 38, 42, 45, 47, 49, 50, 51, 51, 52],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.7, ecValue: 5.7, sccBand: '1+', isAffected: true, statusText: 'Early Drift' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.1, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.2, ecValue: 5.2, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [
      {
        id: 'shap-29-1',
        featureKey: 'thi_cross',
        name: 'Heat Stress + THI Drift',
        nameHi: 'ताप तनाव (THI)',
        nameBn: 'তাপীয় চাপ',
        impactWeight: 0.39,
        deltaValue: 'THI index 79',
        baselineValue: 'THI 70',
        currentValue: 'THI 79',
        explanation: 'HF Cross susceptible to humidity; immune suppression risk.',
        direction: 'increase_risk',
      },
    ],
    actionPlan: {
      urgency: 'MODERATE',
      vetRecommended: false,
      stepsEn: ['Provide misting fans and electrolytes.', 'Check LF teat dip coverage.'],
      stepsHi: ['पंखे व स्वच्छ जल की व्यवस्था करें।'],
      stepsBn: ['ঠাণ্ডা জল ও পর্যাপ্ত বাতাসের ব্যবস্থা করুন।'],
    },
  },
  {
    id: 38,
    tagNumber: 'IN-WB-2024-0038',
    name: 'Meera',
    breed: 'Sahiwal',
    ageYears: 3.5,
    parity: 1,
    lactationDay: 48,
    currentMilkYield: 10.8,
    avgMilkYield: 11.2,
    riskScore: 48,
    riskLevel: 'MODERATE',
    primaryQuarter: 'LR',
    sccCellsPerMl: 390000,
    sccBand: 'Trace',
    tubeTempDiff: 0.6,
    milkEc: 5.5,
    ruminationMin: 460,
    ruminationDropPct: 4,
    activitySteps: 61,
    activityDropPct: 2,
    thiIndex: 72,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 06:18 AM',
    forecast14Days: [15, 16, 18, 20, 24, 28, 32, 36, 40, 42, 44, 46, 47, 48],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.6, ecValue: 5.5, sccBand: 'Trace', isAffected: true, statusText: 'Borderline' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.1, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: {
      urgency: 'ROUTINE',
      vetRecommended: false,
      stepsEn: ['Maintain standard hygiene.'],
      stepsHi: ['सामान्य स्वच्छता बनाए रखें।'],
      stepsBn: ['সাধারণ পরিচ্ছন্নতা বজায় রাখুন।'],
    },
  },
  {
    id: 8,
    tagNumber: 'IN-WB-2024-0008',
    name: 'Kamdhenu',
    breed: 'Sahiwal',
    ageYears: 5.0,
    parity: 3,
    lactationDay: 85,
    currentMilkYield: 14.5,
    avgMilkYield: 14.4,
    riskScore: 18,
    riskLevel: 'HEALTHY',
    primaryQuarter: 'None',
    sccCellsPerMl: 140000,
    sccBand: 'Negative',
    tubeTempDiff: -0.1,
    milkEc: 4.9,
    ruminationMin: 495,
    ruminationDropPct: 0,
    activitySteps: 66,
    activityDropPct: 0,
    thiIndex: 72,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 06:27 AM',
    forecast14Days: [17, 18, 16, 17, 18, 19, 17, 18, 17, 18, 19, 18, 17, 18],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: -0.1, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['No action needed. Healthy herd benchmark.'], stepsHi: ['कोई कार्रवाई आवश्यक नहीं। पूर्णतः स्वस्थ।'], stepsBn: ['কোন ব্যবস্থার প্রয়োজন নেই। সম্পূর্ণ সুস্থ।'] },
  },
  {
    id: 31,
    tagNumber: 'IN-WB-2024-0031',
    name: 'Radha',
    breed: 'HF Cross',
    ageYears: 3.9,
    parity: 2,
    lactationDay: 130,
    currentMilkYield: 17.5,
    avgMilkYield: 17.3,
    riskScore: 24,
    riskLevel: 'LOW',
    primaryQuarter: 'None',
    sccCellsPerMl: 190000,
    sccBand: 'Negative',
    tubeTempDiff: 0.2,
    milkEc: 5.1,
    ruminationMin: 480,
    ruminationDropPct: 2,
    activitySteps: 63,
    activityDropPct: 0,
    thiIndex: 75,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 06:31 AM',
    forecast14Days: [20, 21, 22, 21, 23, 22, 24, 23, 24, 25, 24, 23, 24, 24],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.1, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.2, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Maintain standard sanitation.'], stepsHi: ['नियमित सफाई रखें।'], stepsBn: ['নিয়মিত পরিচ্ছন্নতা বজায় রাখুন।'] },
  },
  {
    id: 12,
    tagNumber: 'IN-WB-2024-0012',
    name: 'Kalyani',
    breed: 'Gir',
    ageYears: 4.8,
    parity: 3,
    lactationDay: 75,
    currentMilkYield: 13.0,
    avgMilkYield: 13.2,
    riskScore: 19,
    riskLevel: 'HEALTHY',
    primaryQuarter: 'None',
    sccCellsPerMl: 155000,
    sccBand: 'Negative',
    tubeTempDiff: 0.1,
    milkEc: 4.95,
    ruminationMin: 510,
    ruminationDropPct: 0,
    activitySteps: 67,
    activityDropPct: 0,
    thiIndex: 71,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 06:05 AM',
    forecast14Days: [18, 17, 19, 18, 19, 18, 19, 18, 17, 19, 18, 19, 18, 19],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Stable condition.'], stepsHi: ['स्थिर स्थिति।'], stepsBn: ['স্থিতিশীল অবস্থা।'] },
  },
  {
    id: 19,
    tagNumber: 'IN-WB-2024-0019',
    name: 'Jamuna',
    breed: 'Sahiwal',
    ageYears: 3.2,
    parity: 1,
    lactationDay: 35,
    currentMilkYield: 10.5,
    avgMilkYield: 10.4,
    riskScore: 16,
    riskLevel: 'HEALTHY',
    primaryQuarter: 'None',
    sccCellsPerMl: 130000,
    sccBand: 'Negative',
    tubeTempDiff: 0.0,
    milkEc: 4.85,
    ruminationMin: 520,
    ruminationDropPct: 0,
    activitySteps: 70,
    activityDropPct: 0,
    thiIndex: 70,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 06:02 AM',
    forecast14Days: [15, 16, 15, 17, 16, 16, 15, 16, 16, 15, 17, 16, 16, 16],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 4.8, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.0, ecValue: 4.8, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Optimal.'], stepsHi: ['उत्तम।'], stepsBn: ['চমৎকার।'] },
  },
  {
    id: 24,
    tagNumber: 'IN-WB-2024-0024',
    name: 'Surabhi',
    breed: 'Gir',
    ageYears: 5.6,
    parity: 4,
    lactationDay: 160,
    currentMilkYield: 12.0,
    avgMilkYield: 12.2,
    riskScore: 22,
    riskLevel: 'LOW',
    primaryQuarter: 'None',
    sccCellsPerMl: 175000,
    sccBand: 'Negative',
    tubeTempDiff: 0.1,
    milkEc: 5.05,
    ruminationMin: 475,
    ruminationDropPct: 1,
    activitySteps: 62,
    activityDropPct: 0,
    thiIndex: 73,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 05:58 AM',
    forecast14Days: [20, 21, 22, 22, 21, 23, 22, 22, 21, 22, 23, 22, 22, 22],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.0, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.1, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Normal.'], stepsHi: ['सामान्य।'], stepsBn: ['স্বাভাবিক।'] },
  },
  {
    id: 3,
    tagNumber: 'IN-WB-2024-0003',
    name: 'Tulsi',
    breed: 'Sahiwal',
    ageYears: 4.0,
    parity: 2,
    lactationDay: 105,
    currentMilkYield: 13.6,
    avgMilkYield: 13.8,
    riskScore: 21,
    riskLevel: 'LOW',
    primaryQuarter: 'None',
    sccCellsPerMl: 160000,
    sccBand: 'Negative',
    tubeTempDiff: 0.1,
    milkEc: 4.95,
    ruminationMin: 490,
    ruminationDropPct: 0,
    activitySteps: 65,
    activityDropPct: 0,
    thiIndex: 72,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 05:50 AM',
    forecast14Days: [19, 20, 21, 20, 21, 22, 21, 21, 20, 21, 22, 21, 21, 21],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Healthy.'], stepsHi: ['स्वस्थ।'], stepsBn: ['সুস্থ।'] },
  },
  {
    id: 9,
    tagNumber: 'IN-WB-2024-0009',
    name: 'Bhavani',
    breed: 'Murrah',
    ageYears: 6.0,
    parity: 4,
    lactationDay: 190,
    currentMilkYield: 14.0,
    avgMilkYield: 14.1,
    riskScore: 27,
    riskLevel: 'LOW',
    primaryQuarter: 'None',
    sccCellsPerMl: 210000,
    sccBand: 'Trace',
    tubeTempDiff: 0.2,
    milkEc: 5.2,
    ruminationMin: 470,
    ruminationDropPct: 1,
    activitySteps: 59,
    activityDropPct: 0,
    thiIndex: 76,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 05:44 AM',
    forecast14Days: [24, 25, 26, 25, 27, 26, 27, 27, 26, 27, 28, 27, 27, 27],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.1, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.2, ecValue: 5.2, sccBand: 'Trace', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.1, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.1, ecValue: 5.2, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Stable.'], stepsHi: ['स्थिर।'], stepsBn: ['স্থিতিশীল।'] },
  },
  {
    id: 14,
    tagNumber: 'IN-WB-2024-0014',
    name: 'Champa',
    breed: 'Jersey Cross',
    ageYears: 3.7,
    parity: 2,
    lactationDay: 110,
    currentMilkYield: 15.0,
    avgMilkYield: 15.2,
    riskScore: 23,
    riskLevel: 'LOW',
    primaryQuarter: 'None',
    sccCellsPerMl: 180000,
    sccBand: 'Negative',
    tubeTempDiff: 0.1,
    milkEc: 5.1,
    ruminationMin: 485,
    ruminationDropPct: 0,
    activitySteps: 64,
    activityDropPct: 0,
    thiIndex: 74,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 05:38 AM',
    forecast14Days: [22, 23, 22, 24, 23, 23, 24, 23, 23, 24, 23, 23, 23, 23],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.1, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.1, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Normal.'], stepsHi: ['सामान्य।'], stepsBn: ['স্বাভাবিক।'] },
  },
  {
    id: 22,
    tagNumber: 'IN-WB-2024-0022',
    name: 'Kapila',
    breed: 'Gir',
    ageYears: 4.3,
    parity: 2,
    lactationDay: 98,
    currentMilkYield: 12.8,
    avgMilkYield: 12.9,
    riskScore: 17,
    riskLevel: 'HEALTHY',
    primaryQuarter: 'None',
    sccCellsPerMl: 145000,
    sccBand: 'Negative',
    tubeTempDiff: 0.0,
    milkEc: 4.9,
    ruminationMin: 505,
    ruminationDropPct: 0,
    activitySteps: 68,
    activityDropPct: 0,
    thiIndex: 71,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 05:30 AM',
    forecast14Days: [16, 17, 16, 17, 18, 17, 17, 16, 17, 18, 17, 17, 17, 17],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Optimal.'], stepsHi: ['उत्तम।'], stepsBn: ['চমৎকার।'] },
  },
  {
    id: 27,
    tagNumber: 'IN-WB-2024-0027',
    name: 'Rohini',
    breed: 'Sahiwal',
    ageYears: 3.6,
    parity: 1,
    lactationDay: 52,
    currentMilkYield: 11.0,
    avgMilkYield: 11.0,
    riskScore: 19,
    riskLevel: 'HEALTHY',
    primaryQuarter: 'None',
    sccCellsPerMl: 150000,
    sccBand: 'Negative',
    tubeTempDiff: 0.1,
    milkEc: 4.95,
    ruminationMin: 490,
    ruminationDropPct: 0,
    activitySteps: 66,
    activityDropPct: 0,
    thiIndex: 72,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 05:22 AM',
    forecast14Days: [18, 19, 18, 19, 20, 19, 19, 18, 19, 20, 19, 19, 19, 19],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Normal.'], stepsHi: ['सामान्य।'], stepsBn: ['স্বাভাবিক।'] },
  },
  {
    id: 33,
    tagNumber: 'IN-WB-2024-0033',
    name: 'Sundari',
    breed: 'HF Cross',
    ageYears: 4.5,
    parity: 2,
    lactationDay: 122,
    currentMilkYield: 16.8,
    avgMilkYield: 17.0,
    riskScore: 28,
    riskLevel: 'LOW',
    primaryQuarter: 'None',
    sccCellsPerMl: 220000,
    sccBand: 'Trace',
    tubeTempDiff: 0.2,
    milkEc: 5.25,
    ruminationMin: 465,
    ruminationDropPct: 1,
    activitySteps: 60,
    activityDropPct: 0,
    thiIndex: 77,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 05:15 AM',
    forecast14Days: [25, 26, 27, 27, 28, 28, 27, 28, 29, 28, 28, 28, 28, 28],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.1, ecValue: 5.2, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.2, ecValue: 5.3, sccBand: 'Trace', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.1, ecValue: 5.2, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.1, ecValue: 5.2, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Normal.'], stepsHi: ['सामान्य।'], stepsBn: ['স্বাভাবিক।'] },
  },
  {
    id: 41,
    tagNumber: 'IN-WB-2024-0041',
    name: 'Mohini',
    breed: 'Murrah',
    ageYears: 5.4,
    parity: 3,
    lactationDay: 150,
    currentMilkYield: 13.5,
    avgMilkYield: 13.7,
    riskScore: 20,
    riskLevel: 'HEALTHY',
    primaryQuarter: 'None',
    sccCellsPerMl: 165000,
    sccBand: 'Negative',
    tubeTempDiff: 0.0,
    milkEc: 4.9,
    ruminationMin: 495,
    ruminationDropPct: 0,
    activitySteps: 65,
    activityDropPct: 0,
    thiIndex: 75,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 05:08 AM',
    forecast14Days: [19, 20, 19, 20, 21, 20, 20, 19, 20, 21, 20, 20, 20, 20],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Stable.'], stepsHi: ['स्थिर।'], stepsBn: ['স্থিতিশীল।'] },
  },
  {
    id: 47,
    tagNumber: 'IN-WB-2024-0047',
    name: 'Pari',
    breed: 'Jersey Cross',
    ageYears: 3.1,
    parity: 1,
    lactationDay: 40,
    currentMilkYield: 14.2,
    avgMilkYield: 14.1,
    riskScore: 15,
    riskLevel: 'HEALTHY',
    primaryQuarter: 'None',
    sccCellsPerMl: 120000,
    sccBand: 'Negative',
    tubeTempDiff: -0.1,
    milkEc: 4.8,
    ruminationMin: 530,
    ruminationDropPct: 0,
    activitySteps: 72,
    activityDropPct: 0,
    thiIndex: 71,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 05:00 AM',
    forecast14Days: [14, 15, 14, 15, 16, 15, 15, 14, 15, 16, 15, 15, 15, 15],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 4.8, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.0, ecValue: 4.8, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: -0.1, ecValue: 4.8, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 4.8, sccBand: 'Negative', isAffected: false, statusText: 'Optimal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Optimal.'], stepsHi: ['उत्तम।'], stepsBn: ['চমৎকার।'] },
  },
  {
    id: 51,
    tagNumber: 'IN-WB-2024-0051',
    name: 'Sita',
    breed: 'Sahiwal',
    ageYears: 4.7,
    parity: 3,
    lactationDay: 115,
    currentMilkYield: 12.4,
    avgMilkYield: 12.6,
    riskScore: 21,
    riskLevel: 'LOW',
    primaryQuarter: 'None',
    sccCellsPerMl: 170000,
    sccBand: 'Negative',
    tubeTempDiff: 0.1,
    milkEc: 5.0,
    ruminationMin: 480,
    ruminationDropPct: 0,
    activitySteps: 63,
    activityDropPct: 0,
    thiIndex: 73,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 04:52 AM',
    forecast14Days: [19, 20, 21, 21, 20, 22, 21, 21, 20, 21, 22, 21, 21, 21],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.1, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.1, ecValue: 5.1, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Normal.'], stepsHi: ['सामान्य।'], stepsBn: ['স্বাভাবিক।'] },
  },
  {
    id: 60,
    tagNumber: 'IN-WB-2024-0060',
    name: 'Anandi',
    breed: 'Gir',
    ageYears: 5.1,
    parity: 3,
    lactationDay: 135,
    currentMilkYield: 13.1,
    avgMilkYield: 13.0,
    riskScore: 18,
    riskLevel: 'HEALTHY',
    primaryQuarter: 'None',
    sccCellsPerMl: 150000,
    sccBand: 'Negative',
    tubeTempDiff: 0.0,
    milkEc: 4.95,
    ruminationMin: 500,
    ruminationDropPct: 0,
    activitySteps: 67,
    activityDropPct: 0,
    thiIndex: 72,
    sensorStatus: 'ONLINE',
    lastMilkedTime: 'Today, 04:45 AM',
    forecast14Days: [17, 18, 17, 18, 19, 18, 18, 17, 18, 19, 18, 18, 18, 18],
    quarters: {
      LF: { code: 'LF', name: 'Left Front', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RF: { code: 'RF', name: 'Right Front', tubeTempDiff: 0.0, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      LR: { code: 'LR', name: 'Left Rear', tubeTempDiff: 0.0, ecValue: 4.9, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
      RR: { code: 'RR', name: 'Right Rear', tubeTempDiff: 0.0, ecValue: 5.0, sccBand: 'Negative', isAffected: false, statusText: 'Normal' },
    },
    shapDrivers: [],
    actionPlan: { urgency: 'ROUTINE', vetRecommended: false, stepsEn: ['Optimal condition.'], stepsHi: ['उत्कृष्ट स्थिति।'], stepsBn: ['চমৎকার অবস্থা।'] },
  },
];

export const INITIAL_ALERTS: AlertNotification[] = [
  {
    id: 'alt-42-01',
    cowId: 42,
    tagNumber: 'IN-WB-2024-0042',
    cowName: 'Ganga',
    timestamp: 'Today, 06:40 AM',
    riskScore: 82,
    riskLevel: 'HIGH',
    quarter: 'LR',
    titleEn: 'HIGH RISK · Cow #42 Ganga (Left Rear Quarter)',
    titleHi: 'उच्च जोखिम · गाय #42 गंगा (बायाँ पिछला थन)',
    titleBn: 'উচ্চ ঝুঁকি · গরু #৪২ গঙ্গা (বাঁ পেছনের বাট)',
    reasonEn: 'SCC band rising for 9 consecutive days; tube heat +1.8°C; rumination down 18%.',
    reasonHi: 'सोमैटिक सेल में 9 दिनों से लगातार वृद्धि; ट्यूब तापमान +1.8°C; जुगाली 18% कम।',
    reasonBn: 'টানা ৯ দিন ধরে এসসিসি বৃদ্ধি; নালীর তাপ +১.৮°C; জাবর কাটা ১৮% কমেছে।',
    actionEn: 'DO TODAY: Milk LR quarter last into separate pot. Teat-dip with iodine. Vet booked tomorrow.',
    actionHi: 'आज करें: LR थन का दूध सबसे अंत में अलग बर्तन में निकालें। टीट-डिप लगाएं। कल डॉक्टर आएंगे।',
    actionBn: 'আজকের কাজ: LR বাটের দুধ শেষে আলাদা পাত্রে দোয়ান। টিট-ডিপ দিন। কাল ডাক্তার আসবেন।',
    read: false,
    smsDispatched: true,
    smsRecipient: '+91 98301 24590',
  },
  {
    id: 'alt-55-01',
    cowId: 55,
    tagNumber: 'IN-WB-2024-0055',
    cowName: 'Nandini',
    timestamp: 'Today, 06:21 AM',
    riskScore: 74,
    riskLevel: 'HIGH',
    quarter: 'RR',
    titleEn: 'HIGH RISK THRESHOLD · Cow #55 Nandini (Right Rear)',
    titleHi: 'उच्च जोखिम सीमा · भैंस #55 नंदिनी (दायाँ पिछला थन)',
    titleBn: 'উচ্চ ঝুঁকি সীমা · মহিষ #৫৫ নন্দিনী (ডান পেছনের বাট)',
    reasonEn: 'MLX90640 tube temp +1.4°C vs healthy baseline; activity down 12%.',
    reasonHi: 'मिल्क-ट्यूब तापमान सामान्य से +1.4°C अधिक; शारीरिक सक्रियता 12% कम।',
    reasonBn: 'দুধের নালীর তাপমাত্রা স্বাভাবিকের চেয়ে +১.৪°C বেশি; চলাফেরা ১২% কমেছে।',
    actionEn: 'Isolate RR milk today; conduct CMT paddle test before evening milking.',
    actionHi: 'आज RR थन का दूध अलग रखें; शाम को दुहने से पहले सीएमटी पैडल टेस्ट करें।',
    actionBn: 'আজ RR বাটের দুধ আলাদা রাখুন; সন্ধ্যার আগে সিএমটি পরীক্ষা করুন।',
    read: false,
    smsDispatched: true,
    smsRecipient: '+91 98301 24590',
  },
  {
    id: 'alt-17-01',
    cowId: 17,
    tagNumber: 'IN-WB-2024-0017',
    cowName: 'Lakshmi',
    timestamp: 'Yesterday, 06:35 PM',
    riskScore: 61,
    riskLevel: 'MODERATE',
    quarter: 'RF',
    titleEn: 'MODERATE DRIFT · Cow #17 Lakshmi (Right Front)',
    titleHi: 'मध्यम बदलाव · गाय #17 लक्ष्मी (दायाँ अगला थन)',
    titleBn: 'মাঝারি পরিবর্তন · গরু #১৭ লক্ষ্মী (ডান সামনের বাট)',
    reasonEn: 'Conductivity (EC) slope rising over 7 days. Subclinical window detected.',
    reasonHi: '7 दिनों से विद्युत चालकता (EC) में निरंतर वृद्धि। मस्टाइटिस पूर्व लक्षण।',
    reasonBn: 'গত ৭ দিন ধরে তড়িৎ পরিবাহিতা (EC) ক্রমাগত বৃদ্ধি পাচ্ছে।',
    actionEn: 'Monitor next 24 hours. Pre-dip teat with disinfectant before milking.',
    actionHi: 'अगले 24 घंटे निगरानी रखें। दुहने से पहले थन को अच्छी तरह साफ करें।',
    actionBn: 'পরবর্তী ২৪ ঘণ্টা লক্ষ্য রাখুন। দোহনের আগে বাট জীবাণুমুক্ত করুন।',
    read: true,
    smsDispatched: false,
    smsRecipient: '+91 98301 24590',
  },
];

export const INITIAL_VET_CASES: VetCase[] = [
  {
    id: 'VET-CASE-101',
    cowId: 42,
    cowName: 'Ganga',
    tagNumber: 'IN-WB-2024-0042',
    farmName: 'Das Dairy Farm (Arun Das)',
    district: 'Nadia',
    riskScore: 82,
    affectedQuarter: 'LR',
    submittedAt: 'Today, 06:45 AM',
    status: 'PENDING_REVIEW',
    labeledForTraining: false,
  },
  {
    id: 'VET-CASE-102',
    cowId: 55,
    cowName: 'Nandini',
    tagNumber: 'IN-WB-2024-0055',
    farmName: 'Das Dairy Farm (Arun Das)',
    district: 'Nadia',
    riskScore: 74,
    affectedQuarter: 'RR',
    submittedAt: 'Today, 06:25 AM',
    status: 'PENDING_REVIEW',
    labeledForTraining: false,
  },
  {
    id: 'VET-CASE-098',
    cowId: 104,
    cowName: 'Shyama',
    tagNumber: 'IN-WB-2024-0104',
    farmName: 'Mondal Krishi Farm',
    district: 'Hooghly',
    riskScore: 88,
    affectedQuarter: 'LR',
    submittedAt: '2 days ago',
    status: 'CONFIRMED_SUBCLINICAL',
    pathogenIsolated: 'Staphylococcus aureus',
    treatmentRegimen: 'Intramammary Cloxacillin (Targeted 1-quarter)',
    withholdingDays: 3,
    vetNotes: 'Caught at Day -8 lead-time before udder hardened. Full recovery in 48h. Saved whole lactation.',
    labeledForTraining: true,
  },
  {
    id: 'VET-CASE-095',
    cowId: 88,
    cowName: 'Rani',
    tagNumber: 'IN-WB-2024-0088',
    farmName: 'Ghosh Goshala',
    district: 'Howrah',
    riskScore: 54,
    affectedQuarter: 'RF',
    submittedAt: '4 days ago',
    status: 'FALSE_POSITIVE',
    pathogenIsolated: 'Negative culture (Clean)',
    treatmentRegimen: 'Topical herbal spray only',
    vetNotes: 'Temporary EC rise caused by mild teat scratch. Re-calibrated threshold.',
    labeledForTraining: true,
  },
];

export const INITIAL_DISTRICT_HOTSPOTS: DistrictHotspot[] = [
  {
    id: 'dist-nadia',
    districtName: 'Nadia',
    state: 'West Bengal',
    farmsCount: 15,
    cowsMonitored: 312,
    herdRiskIndex: 68,
    highRiskAlerts: 7,
    moderateRiskAlerts: 11,
    bulkTankScc: 420000,
    milkQualityGrade: 'B',
    status: 'ALERT_HOTSPOT',
    coordinates: { x: 38, y: 32 },
  },
  {
    id: 'dist-hooghly',
    districtName: 'Hooghly',
    state: 'West Bengal',
    farmsCount: 12,
    cowsMonitored: 248,
    herdRiskIndex: 52,
    highRiskAlerts: 4,
    moderateRiskAlerts: 6,
    bulkTankScc: 340000,
    milkQualityGrade: 'B',
    status: 'MONITOR',
    coordinates: { x: 44, y: 48 },
  },
  {
    id: 'dist-howrah',
    districtName: 'Howrah',
    state: 'West Bengal',
    farmsCount: 9,
    cowsMonitored: 186,
    herdRiskIndex: 38,
    highRiskAlerts: 2,
    moderateRiskAlerts: 4,
    bulkTankScc: 260000,
    milkQualityGrade: 'A',
    status: 'NORMAL',
    coordinates: { x: 50, y: 62 },
  },
  {
    id: 'dist-n24p',
    districtName: 'North 24 Parganas',
    state: 'West Bengal',
    farmsCount: 18,
    cowsMonitored: 395,
    herdRiskIndex: 44,
    highRiskAlerts: 5,
    moderateRiskAlerts: 8,
    bulkTankScc: 290000,
    milkQualityGrade: 'A',
    status: 'MONITOR',
    coordinates: { x: 62, y: 42 },
  },
  {
    id: 'dist-karnal',
    districtName: 'Karnal (ICAR-NDRI)',
    state: 'Haryana',
    farmsCount: 4,
    cowsMonitored: 180,
    herdRiskIndex: 22,
    highRiskAlerts: 1,
    moderateRiskAlerts: 2,
    bulkTankScc: 190000,
    milkQualityGrade: 'A',
    status: 'NORMAL',
    coordinates: { x: 22, y: 20 },
  },
  {
    id: 'dist-anand',
    districtName: 'Anand (AMUL Hub)',
    state: 'Gujarat',
    farmsCount: 24,
    cowsMonitored: 520,
    herdRiskIndex: 18,
    highRiskAlerts: 2,
    moderateRiskAlerts: 5,
    bulkTankScc: 180000,
    milkQualityGrade: 'A',
    status: 'NORMAL',
    coordinates: { x: 18, y: 55 },
  },
];
